import { addIcons } from 'ionicons';
import {
  personOutline,
  lockClosedOutline,
  warningOutline,
  peopleOutline,
  gridOutline,
  documentTextOutline,
  analyticsOutline,
  timeOutline,
  listOutline,
  personAddOutline,
  logOutOutline,
  alertCircleOutline,
  checkmarkCircle,
  closeCircle,
  playCircle,
  pauseCircle,
  warning,
  time,
  camera,
  downloadOutline,
  folderOpenOutline,
  peopleCircleOutline,
  documentOutline,
  cloudUploadOutline,
  addOutline,
  createOutline,
  homeOutline,
  informationCircleOutline,
  refreshOutline,
  barChartOutline,
  trashOutline,
  speedometerOutline,
  calendarOutline,
  trendingUpOutline,
  calculatorOutline,
  chevronUpOutline,
  chevronDownOutline,
  hourglassOutline,
  clipboardOutline,
  checkmarkCircleOutline,
  closeOutline,
  chevronBackOutline,
  todayOutline,
  chevronForwardOutline,
  people,
  settings,
  search,
  filter,
  refresh,
  optionsOutline,
  statsChartOutline,
  addCircleOutline,
  hardwareChip,
  personAdd,
  cube,
  calendar,
  flag,
  build,
  person,
  chevronBack,
  chevronForward,
  flash,
  business,
  albums,
  checkmark,
  close,
  imagesOutline,
  arrowBack,
  arrowBackOutline,
  arrowUndoOutline,
  lockClosed
} from 'ionicons/icons';

/**
 * 注册所有应用中使用的图标
 */
export function registerIcons() {
  addIcons({
    'person-outline': personOutline,
    'lock-closed-outline': lockClosedOutline,
    'warning-outline': warningOutline,
    'people-outline': peopleOutline,
    'grid-outline': gridOutline,
    'document-text-outline': documentTextOutline,
    'analytics-outline': analyticsOutline,
    'time-outline': timeOutline,
    'list-outline': listOutline,
    'person-add-outline': personAddOutline,
    'log-out-outline': logOutOutline,
    'alert-circle-outline': alertCircleOutline,
    'checkmark-circle': checkmarkCircle,
    'close-circle': closeCircle,
    'play-circle': playCircle,
    'pause-circle': pauseCircle,
    'warning': warning,
    'time': time,
    'camera': camera,
    'download-outline': downloadOutline,
    'folder-open-outline': folderOpenOutline,
    'people-circle-outline': peopleCircleOutline,
    'document-outline': documentOutline,
    'cloud-upload-outline': cloudUploadOutline,
    'add-outline': addOutline,
    'create-outline': createOutline,
    'home-outline': homeOutline,
    'information-circle-outline': informationCircleOutline,
    'refresh-outline': refreshOutline,
    'bar-chart-outline': barChartOutline,
    'trash-outline': trashOutline,
    'speedometer-outline': speedometerOutline,
    'calendar-outline': calendarOutline,
    'trending-up-outline': trendingUpOutline,
    'calculator-outline': calculatorOutline,
    'chevron-up-outline': chevronUpOutline,
    'chevron-down-outline': chevronDownOutline,
    'hourglass-outline': hourglassOutline,
    'calculations-outline': calculatorOutline, // 使用 calculatorOutline 作为替代
    'clipboard-outline': clipboardOutline,
    'checkmark-circle-outline': checkmarkCircleOutline,
    'close-outline': closeOutline,
    'chevron-back-outline': chevronBackOutline,
    'today-outline': todayOutline,
    'chevron-forward-outline': chevronForwardOutline,
    'people': people,
    'settings': settings,
    'search': search,
    'filter': filter,
    'refresh': refresh,
    'options-outline': optionsOutline,
    'stats-chart-outline': statsChartOutline,
    'add-circle-outline': addCircleOutline,
    'hardware-chip': hardwareChip,
    'person-add': personAdd,
    'cube': cube,
    'calendar': calendar,
    'flag': flag,
    'build': build,
    'person': person,
    'chevron-back': chevronBack,
    'chevron-forward': chevronForward,
    'flash': flash,
    'business': business,
    'albums': albums,
    'checkmark': checkmark,
    'close': close,
    'images-outline': imagesOutline,
    'arrow-back': arrowBack,
    'arrow-back-outline': arrowBackOutline,
    'arrow-undo-outline': arrowUndoOutline,
    'lock-closed': lockClosed
  });
}
